#!/bin/bash

echo "📱 文件管理器 - 本地预览"
echo "=========================="
echo ""
echo "如果您在本地电脑上运行此项目："
echo ""
echo "1️⃣ 安装依赖："
echo "   npm install"
echo ""
echo "2️⃣ 启动开发服务器："
echo "   npm run dev"
echo ""
echo "3️⃣ 查看您的电脑IP地址："
echo "   Windows: ipconfig"
echo "   Mac/Linux: ifconfig"
echo ""
echo "4️⃣ 在手机浏览器访问："
echo "   http://您电脑的IP:5173/"
echo ""
echo "🚀 祝您使用愉快！"
